#!/usr/bin/env python3
from collections import defaultdict
import argparse


def main():
    p = argparse.ArgumentParser()
    p.add_argument("-f", "--fasta_alignments", type=argparse.FileType("r"),
                   help="Input fasta from the extracted CDS of the alignments")

    args = p.parse_args()
    alignments_filename = args.fasta_alignments.name
    alignments_fa = []
    with open(alignments_filename) as fasta:
        for line in fasta:
            if line[0] != ">":
                continue
            alignments_fa.append(line.strip()[1:])

    gene_to_group = defaultdict(list)
    for k in alignments_fa:
        gene_to_group['.'.join(k.split('.')[:-1])].append(k)

    groupid = 0
    with open("groups.txt", "w") as gf:
        for k, v in gene_to_group.items():
            groupid += 1
            print('.'.join([k]), groupid, file=gf)
            for a in v:
                print(a, groupid, file=gf)


if __name__ == '__main__':
    main()

