#!/usr/bin/env python3
import argparse

from annotation import minimal_gxf_parser


def gff_to_zff(gff_file):
    current_chrom = ""
    genes, tid2gid = minimal_gxf_parser(gff_file)
    for gene in genes:
        for mrna in genes[gene].transcripts.values():
            num_coding_exons = len(mrna.coding_exons)
            if num_coding_exons == 0:
                continue
            if mrna.chrom != current_chrom:
                current_chrom = mrna.chrom
                print(f">{current_chrom}")
            if num_coding_exons == 1:
                print('Esngl', mrna.coding_exons[0][0], mrna.coding_exons[0][1], mrna.id, sep='\t')

            elif num_coding_exons > 1:
                print('Einit', mrna.coding_exons[0][0], mrna.coding_exons[0][1], mrna.id, sep='\t')
                for cds in mrna.coding_exons[1:-1]:
                    print('Exon', cds[0], cds[1], mrna.id, sep='\t')
                print('Eterm', mrna.coding_exons[-1][0], mrna.coding_exons[-1][1], mrna.id, sep='\t')


def main():

    p = argparse.ArgumentParser()
    p.add_argument("-a", "--annotation", type=argparse.FileType('r'),
                   help="GFF file of the annotated species to extract proteins from")
    args = p.parse_args()
    gff_file = args.annotation
    gff_to_zff(gff_file.name)


if __name__ == "__main__":
    main()
