#!/usr/bin/env python3
import argparse

from annotation import minimal_gxf_parser


def gff_to_glimmer(gff_file):
    first = True
    genes, tid2gid = minimal_gxf_parser(gff_file)
    for gene in genes:
        for mrna in genes[gene].transcripts.values():
            num_coding_exons = len(mrna.coding_exons)
            if num_coding_exons == 0:
                continue
            if not first:
                print()
            else:
                first = False
            for c in mrna.coding_exons:
                print(f"{mrna.chrom} {c[0]} {c[1]}")


def main():
    p = argparse.ArgumentParser()
    p.add_argument("-a", "--annotation", type=argparse.FileType('r'),
                   help="GFF file of the annotated species to extract proteins from")
    args = p.parse_args()
    gff_file = args.annotation
    gff_to_glimmer(gff_file.name)


if __name__ == "__main__":
    main()
