#!/usr/bin/env python3

import csv
import json
import sys

input_aligned_samples = json.load(open(sys.argv[1]))
aligned_samples = {}
for sample in input_aligned_samples:
    aligned_samples[sample['name']] = {
        "strand": sample['strand'],
        "aligner": sample['aligner'],
        "bam": sample['bam']
    }

group_to_sample = json.load(open(sys.argv[2]))
portcullis_groups = []
group_to_index = {}
group_count = 0
for gts in group_to_sample:
    group = gts['left']
    samples = gts['right']
    group_to_index[group] = group_count
    group_count += 1
    portcullis_groups.append({
        "name": group,
        "aligner": "*",
        "strand": "",
        "bam": []
    })
    for sample in samples:
        portcullis_groups[group_to_index[group]]["strand"] = aligned_samples[sample.strip(' ')]['strand']
        portcullis_groups[group_to_index[group]]["bam"].extend(aligned_samples[sample.strip(' ')]['bam'])

for group in portcullis_groups:
    outfile = open(group['name'] + "_" + group["strand"] + '.sample', "w")
    for bam in group["bam"]:
        print(bam, file=outfile)
