name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install system development tools
        if: startsWith(runner.os, 'Linux')
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt update
          sudo apt install -y build-essential zlib1g-dev zlib1g
      - uses: actions/cache@v2
        if: startsWith(runner.os, 'Linux')
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Cache conda
        id: cache-miniconda
        uses: actions/cache@v2
        env:
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('./reat.yml') }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          miniconda-version: "latest"
          environment-file: ./reat.yml
          mamba-version: "*"
          use-mamba: true
          channels: conda-forge, defaults
          use-only-tar-bz2: true  # IMPORTANT: This needs to be set for caching to work properly!
          activate-environment: "REAT"
      - name: Install dependencies
        run: |
          wget -O cromwell.jar https://github.com/broadinstitute/cromwell/releases/download/63/cromwell-63.jar
          pip install pytest-workflow
          pip install .
      - name: CLI test
        run: |
          ls -l
          echo $(readlink -f cromwell.jar)
          export CROMWELL_JAR=$(readlink -f cromwell.jar)
          echo $(readlink -f cromwell_configuration/cromwell.local.conf)
          export CROMWELL_RUNTIME_CONFIG=$(readlink -f cromwell_configuration/cromwell.local.conf)
          pytest --tag cli --symlink --kwd --basetemp ../pytest_temp
      - name: Release
        uses: softprops/action-gh-release@v1
