name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install system development tools
        run: |
          export DEBIAN_FRONTEND=noninteractive
          sudo apt update
          sudo apt install -y build-essential zlib1g-dev zlib1g
      - name: Conda setup
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.8
          miniconda-version: "latest"
          environment-file: ./reat.yml
          mamba-version: "*"
          use-mamba: true
          channels: conda-forge, defaults
          use-only-tar-bz2: true
          activate-environment: "REAT"
      - name: Install dependencies
        run: |
          wget -O cromwell.jar https://github.com/broadinstitute/cromwell/releases/download/63/cromwell-63.jar
          pip install pytest-workflow
          pip install .
          reat --help
      - name: CLI test
        run: |
          export CROMWELL_JAR=$(readlink -f cromwell.jar)
          export CROMWELL_RUNTIME_CONFIG=$(readlink -f cromwell_configuration/cromwell.local.conf)
          pytest --tag cli --symlink --kwd --basetemp ../pytest_temp
      - name: Release
        uses: softprops/action-gh-release@v1
